{% set python_min = "3.11" %}
{% set name = "clapper" %}
{% set version = "1.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/clapper-{{ version }}.tar.gz
  sha256: 6b2740f0864e614964ae5136edf839019b7f007f2e4b5b4760d13095c0f233a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - versioningit
    - pip
  run:
    - python >={{ python_min }}
    - click >=8
    - tomli
    - tomli-w
    - xdg
    - __unix

test:
  source_files:
    - tests
  imports:
    - clapper
  commands:
    - pip check
    - pytest -sv tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/idiap/clapper
  doc_url: https://clapper.readthedocs.io
  dev_url: https://github.com/idiap/clapper
  summary: Configuration Support for Python Packages and CLIs
  license: BSD-3-Clause
  license_file: LICENSES/BSD-3-Clause.txt

extra:
  recipe-maintainers:
    - Yannick-Dayer
    - anjos
